BULK_FILE: /data/pye/LaRCH/data/mean_tpm_merged.csv
DATA_DIR: /data/pye/LaRCH/data/sim_data_trial
OUTPUT_DIR: /data/pye/LaRCH/models/sim_data_trial
LOG_DIR: /data/pye/LaRCH/logs
WORKING_DIR: /home/BCCRC.CA/pye/projects/SuSiEVAE

SIMULATION_PARAMETERS:
  N: 2000
  D: 2000
  NOISE: [0.0, 0.25, 0.5, 0.75, 0.9, 0.95, 0.975, 0.99, 0.995, 1.0]
  SEED: [111, 222, 333, 444, 555, 666, 777, 888, 999, 123]

TREE_VAE_PARAMETERS:
  TREE_DEPTH: 5
  EPOCHS: 1000
  LR: 0.01
  BS: 128
  PIP0: 0.1
  KL_WEIGHT: 1.0
  KL_WEIGHT_BETA: 1.0
  A0: 0.000001
  TRAIN_SIZE: 1.0
  SEED: 123
  USE_GPU: 0
  CHECK_VAL_EVERY_N_EPOCH: 1
  DATA_ID: sim_data_trial


# example snakemake command: `snakemake --snakefile snakemake/Snakefile --configfile snakemake/config --cores 4`