---
title: "Tree SuSiE VAE Experiments"
author: Yichen Zhang
date: "`r format(Sys.time(), ' %X, %b %d, %Y')`"
fontsize: 11pt
---
```{r setup, message=FALSE}
library(aricode)
library(data.table)
library(dplyr)
library(knitr)
library(gplots)
library(ComplexHeatmap)
source("util.R")
```

## Topic proportions, topic loading, node loading, anchor genes
```{r, heatmapdat, cache=TRUE}
dat <- readRDS("data/sim_tree.rda")
dat$param_list
apply(dat$theta, 1, which.max) %>% table() %>% kable
dat$theta %>% Heatmap()
#dat$rho %>% as.matrix() %>% heatmap()
#dat$A %>% heatmap()
dat$beta_topic %>% as.matrix() %>% heatmap()
dat$beta_node %>% as.matrix() %>% heatmap()
dat$anchor_gene_mat %>% heatmap()
```

## Topic propoitions (estimated from the model)
```{r heatmap est, cache=T, echo=F}
model_path <-"tree_spike_slab_ep2000_treeD5_bs128_lr0.01_train_size1_pip0.1_kl0.1_klbeta1_seed66"
topics_est <- as.matrix(fread(paste0(model_path, "/topics.csv")), rownames = 1)
apply(topics_est, 1, which.max) %>% table() %>% kable()
heatmap(topics_est)
```

## Normalized Mutual Information (NMI)
```{r NMI}
### Normalized Mutual Information
NMI(paste0("topic", c(apply(topics_est, 1, which.max))), c(t(apply(dat$theta, 1, which.max))))
```

```{r, echo = FALSE}
Save_Path <- model_path
.genes <- fread(paste0(Save_Path, "/var_names.csv"))
setnames(.genes, "V1", "gene")
readDT_melt <- function(Save_Path, parameter, target){
    readpath <- paste0(Save_Path, "/model_parameters/", paste0(parameter, "_", target, ".txt"))
    a <- fread(readpath)
    a[, Var1 := rownames(a)] %>% reshape2::melt(id.vars = "Var1", value.name = parameter)
}

target <- "rho"
file <- paste0(Save_Path, "/dt_rho.rds")
if(!file.exists(file)){
    param.dt.rho <- readDT_melt(Save_Path, "slab_mean", target) %>%
        merge(readDT_melt(Save_Path, "slab_lnvar", target), allow.cartesian = TRUE) %>%
        merge(readDT_melt(Save_Path, "spike_logit", target), allow.cartesian = TRUE) %>%
        mutate(pip = 1/(1 + exp(-spike_logit))) %>%
        mutate(row = `Var1`, col = `variable`, weight = slab_mean * pip) %>%
        mutate(parameter := target)
    saveRDS(param.dt.rho, file)
}
param.dt.rho <- readRDS(file)

dcast(param.dt.rho, row  ~ col, value.var = "weight") -> weight.mat.rho
weight.mat.rho %>% data.matrix() -> weight.mat.rho
rownames(weight.mat.rho) <- weight.mat.rho[, 1]
weight.mat.rho <- weight.mat.rho[, 2:ncol(weight.mat.rho)]
```

## Heatmap of the estimated weights (all nodes)
```{r, echo = F, cache=T}
weight.mat.rho %>% as.matrix() -> beta_node_est
colnames(beta_node_est) <- paste0("g", 1:ncol(beta_node_est))

# only on non-zero genes
dat$anchor_gene_mat[, colSums(dat$anchor_gene_mat) > 0] -> tmp

label <- rep(NA, ncol(tmp))
for(i in 1:nrow(tmp)){
    label[(tmp[i,]>0)] <- rownames(tmp)[i]
}
label_layer <- label
label_layer[label %in% paste0("tr", 1)] <- 1
label_layer[label %in% paste0("tr", 2:3)] <- 2
label_layer[label %in% paste0("tr", 4:7)] <- 3
label_layer[label %in% paste0("tr", 8:15)] <- 4

ha <- HeatmapAnnotation(node = label, 
                      layer = label_layer, 
                      col = list(layer = c("1" = "red", 
                      "2" = "green", 
                      "3" = "blue", 
                      "4" = "yellow")))

beta_node_est %>% Heatmap()

beta_node_est[, colnames(tmp)] %>% Heatmap(top_annotation = ha)

```


```{r, echo=F}
# how many genes are picked in beta_topic_est the anchor genes
n_top <- dat$param_list$S
n_top <- 500
mat_node <- matrix(nrow = nrow(beta_node_est), ncol = nrow(dat$anchor_gene_mat))
rownames(mat_node) <- paste0(1:nrow(beta_node_est), "_hat")

for(i in 1:nrow(mat_node)){
    for(j in 1:ncol(mat_node)){
        sum((rank(-beta_node_est[i,]) <= n_top) * dat$anchor_gene_mat[j,]) -> mat_node[i,j]
    }
}
corrplot::corrplot(mat_node, is.corr = FALSE, 
                    method = "color",
                    col.lim=c(0, max(mat_node)), 
                    addgrid.col = 'white', 
                    addCoef.col = 'grey50')
```
```{r}
K_est <- 5 
K <- dat$param_list$D_tree
mat_layer <- matrix(nrow = K_est, ncol = K)
for(i in 1:K_est){
    for(j in 1:K){
        mat_layer[i, j] <- mat_node[2^(i-1):(2^i-1),2^(j-1):(2^j-1)] %>% sum()
    }
}
corrplot::corrplot(mat_layer, is.corr = FALSE, 
                    method = "color",
                    #col.lim=c(0, max(mat_layer)), 
                    addgrid.col = 'white', 
                    addCoef.col = 'grey50')

```

# hypergeometric test layer wise
```{r}
for(i in 1:4){
    K = K_est = i; phyper(mat_layer[K_est,K], 50*(2^(K-1)), 10000-50*(2^(K-1)), n_top*(2^(K_est-1)), lower.tail = F) -> p
    
    print(paste0("Layer-", i, " p-val:", p))
}

print("Layer-5")
K = 4; K_est = 5; phyper(mat_layer[K_est,K], 50*(2^(K-1)), 10000-50*(2^(K-1)), n_top*(2^(K_est-1)), lower.tail = F)

```

```{r}
for(i in 1:4){
    K =i
    K_est = i;
    p <- phyper(sum(mat_layer[1:K_est,K]), 50*((2^K)-1), 10000-50*((2^K)-1), n_top*(2^(K_est- 1)), lower.tail = F)
    print(paste0("Layer-", i, " accumulate p-val:", p))
}
print("Layer-5")
K = 4; K_est = 5;
phyper(sum(mat_layer[1:K_est,K]), 50*((2^K)-1), 10000-50*((2^K)-1), n_top*(2^(K_est- 1)), lower.tail = F)
```